name       : displaycal
version    : 3.6.0.0
release    : 10
source     :
    - https://kent.dl.sourceforge.net/project/dispcalgui/release/3.6.0.0/DisplayCAL-3.6.0.0.tar.gz : 6ff81011f8d4f28ea25dc3d2d61dd216d4670e4637172f87e9e3c74c1a471a1c
homepage   : https://displaycal.net/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Display Calibration and Characterization powered by Argyll CMS
description: |
    DisplayCAL is a graphical user interface developed by Florian Höch for the display calibration and profiling tools of Argyll CMS, an open source color management system developed by Graeme Gill.
    Calibrate and characterize your display devices using one of the many supported hardware sensors, with support for multi-display setups and a variety of available settings like customizable whitepoint, luminance, tone response curve as well as the option to create matrix and look-up-table ICC profiles, with optional gamut mapping, as well as some proprietary 3D LUT formats.
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
rundeps    :
    - numpy
    - wxPython
    - argyllcms
build      : |
    %python_setup
install    : |
    %python_install --optimize=1
    # Use hwdata pnp.ids
    rm -v $installdir/usr/share/DisplayCAL/pnp.ids
