name       : displaycal
version    : 3.3.4.0
release    : 5
source     :
    - https://pilotfiber.dl.sourceforge.net/project/dispcalgui/release/3.3.4.0/DisplayCAL-3.3.4.0.tar.gz : 08d8fa49dce6e81496949d5f5a1e9d22c028fc39c23dfc4ce9c8ce4c5e0f31c1
license    : GPL-3.0
component  : multimedia.graphics
summary    : Display Calibration and Characterization powered by Argyll CMS
description: |
    DisplayCAL is a graphical user interface developed by Florian Höch for the display calibration and profiling tools of Argyll CMS, an open source color management system developed by Graeme Gill.
    Calibrate and characterize your display devices using one of the many supported hardware sensors, with support for multi-display setups and a variety of available settings like customizable whitepoint, luminance, tone response curve as well as the option to create matrix and look-up-table ICC profiles, with optional gamut mapping, as well as some proprietary 3D LUT formats.
homepage   : https://displaycal.net/
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
rundeps    :
    - numpy
    - wxPython
    - argyllcms
build      : |
    %python_setup
install    : |
    %python_install
    # Use hwdata pnp.ids
    rm -v $installdir/usr/share/DisplayCAL/pnp.ids
