name       : displaycal
version    : 3.1.7.2
release    : 1
source     :
    - http://pilotfiber.dl.sourceforge.net/project/dispcalgui/release/3.1.7.2/DisplayCAL-3.1.7.2.tar.gz : fb5867dbea7a33ff6d064c5a1289357bc84a51876dee108a135982a7370f3d80
license    : GPL-3.0
component  : multimedia.graphics
summary    : A graphical user interface for display calibration
description: |
    A graphical user interface for display calibration
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
rundeps    :
    - numpy
    - wxPython
build      : |
    %python_setup    
install    : |
    %python_install
