name       : displaycal
version    : 3.7.1.1
release    : 15
source     :
    - https://kent.dl.sourceforge.net/project/dispcalgui/release/3.7.1.1/DisplayCAL-3.7.1.1.tar.gz : e0e647266795a0dac15263026df297fc9e09cc88a52ae3bb60d4a61800ae2ac2
homepage   : https://displaycal.net/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Display Calibration and Characterization powered by Argyll CMS
description: |
    DisplayCAL is a graphical user interface developed by Florian Höch for the display calibration and profiling tools of Argyll CMS, an open source color management system developed by Graeme Gill.
    Calibrate and characterize your display devices using one of the many supported hardware sensors, with support for multi-display setups and a variety of available settings like customizable whitepoint, luminance, tone response curve as well as the option to create matrix and look-up-table ICC profiles, with optional gamut mapping, as well as some proprietary 3D LUT formats.
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
rundeps    :
    - numpy
    - wxPython
    - argyllcms
build      : |
    %python_setup
install    : |
    %python_install --optimize=1
    # Use hwdata pnp.ids
    rm -v $installdir/usr/share/DisplayCAL/pnp.ids
