name       : displaycal
version    : 3.4.0.0
release    : 8
source     :
    - https://kent.dl.sourceforge.net/project/dispcalgui/release/3.4.0.0/DisplayCAL-3.4.0.0.tar.gz : 0bf77f854aa89a3efb23fa4688e7c7435aa53c6a943b785f362ac8c2d64c0e36
license    : GPL-3.0
component  : multimedia.graphics
summary    : Display Calibration and Characterization powered by Argyll CMS
description: |
    DisplayCAL is a graphical user interface developed by Florian Höch for the display calibration and profiling tools of Argyll CMS, an open source color management system developed by Graeme Gill.
    Calibrate and characterize your display devices using one of the many supported hardware sensors, with support for multi-display setups and a variety of available settings like customizable whitepoint, luminance, tone response curve as well as the option to create matrix and look-up-table ICC profiles, with optional gamut mapping, as well as some proprietary 3D LUT formats.
homepage   : https://displaycal.net/
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
rundeps    :
    - numpy
    - wxPython
    - argyllcms
build      : |
    %python_setup
install    : |
    %python_install --optimize=1
    # Use hwdata pnp.ids
    rm -v $installdir/usr/share/DisplayCAL/pnp.ids
