name       : displaycal
version    : 3.8.9.3
release    : 27
source     :
    - https://netcologne.dl.sourceforge.net/project/dispcalgui/release/3.8.9.3/DisplayCAL-3.8.9.3.tar.gz : 7c34dfbd9f66f24f1d4c88de4a5a0de688aad719f095874b6259637d30893bea
homepage   : https://displaycal.net/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Display Calibration and Characterization powered by Argyll CMS
description: |
    DisplayCAL is a graphical user interface developed by Florian Höch for the display calibration and profiling tools of Argyll CMS, an open source color management system developed by Graeme Gill.
    Calibrate and characterize your display devices using one of the many supported hardware sensors, with support for multi-display setups and a variety of available settings like customizable whitepoint, luminance, tone response curve as well as the option to create matrix and look-up-table ICC profiles, with optional gamut mapping, as well as some proprietary 3D LUT formats.
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
rundeps    :
    - argyllcms
    - python2-numpy
    - python-gobject
    - wxPython
setup      : |
    %patch -p1 < $pkgfiles/0001-Move-content-out-of-etc.patch
build      : |
    %python_setup
install    : |
    %python_install --optimize=1
    # Use hwdata pnp.ids
    rm -v $installdir/usr/share/DisplayCAL/pnp.ids
