name       : displaycal
version    : 3.9.11
release    : 28
source     :
    - https://github.com/eoyilmaz/displaycal-py3/releases/download/3.9.11/DisplayCAL-3.9.11.tar.gz : cc0656d9e323c1161ebe5cfc284cd3c7318ef2fc7903275f637bc64daa4da357
    - https://raw.githubusercontent.com/eoyilmaz/displaycal-py3/main/misc/net.displaycal.DisplayCAL.appdata.xml : 88115e7026e42328f5516979360284f702a4ae10b86be6053b4dae4e5280a6fb
homepage   : https://displaycal.net/
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : Display Calibration and Characterization powered by Argyll CMS
description: |
    DisplayCAL is a graphical user interface developed by Florian Höch for the display calibration and profiling tools of Argyll CMS, an open source color management system developed by Graeme Gill.
    Calibrate and characterize your display devices using one of the many supported hardware sensors, with support for multi-display setups and a variety of available settings like customizable whitepoint, luminance, tone response curve as well as the option to create matrix and look-up-table ICC profiles, with optional gamut mapping, as well as some proprietary 3D LUT formats.
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(python3)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xxf86vm)
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - argyllcms
    - numpy
    - python-distro
    - python-gobject
    - python-send2trash
    - wxPython
build      : |
    # FIXME: Should be resolved by next release
    install -Dm00644 $sources/net.displaycal.DisplayCAL.appdata.xml $workdir/dist/net.displaycal.DisplayCAL.appdata.xml
    python3 -m build --wheel --no-isolation
install    : |
    python3 -m installer --destdir=$installdir dist/*.whl
    # Use hwdata pnp.ids
    rm -v $installdir/usr/share/DisplayCAL/pnp.ids
# having python-pyglet v2+ installed causes displaycal to shit itself during startup
# this is due to pyglet 1.5 being used as the audio library on macos/windows.
conflicts  : python-pyglet
